### ISSUE TITLE
Genotype Error

### ISSUE THREAD

**Issue by BrendaLee1** [mehrdadbakhtiari/adVNTR#42]
Hi!
The following error always occur when I run genotype command on pacbio bam file: 
   Traceback (most recent call last):
  File "/soft/Anaconda/anaconda3/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/soft/Anaconda/anaconda3/lib/python3.6/site-packages/advntr/__main__.py", line 134, in main
    genotype(args, genotype_parser)
  File "/soft/Anaconda/anaconda3/lib/python3.6/site-packages/advntr/advntr_commands.py", line 114, in genotype
    genome_analyzier.find_repeat_counts_from_pacbio_alignment_file(input_file)
  File "/soft/Anaconda/anaconda3/lib/python3.6/site-packages/advntr/genome_analyzer.py", line 214, in find_repeat_counts_from_pacbio_alignment_file
    self.print_genotype(vid, copy_numbers)
  File "/soft/Anaconda/anaconda3/lib/python3.6/site-packages/advntr/genome_analyzer.py", line 31, in print_genotype
    self.print_genotype_in_vcf(vntr_id, genotype_result)
  File "/soft/Anaconda/anaconda3/lib/python3.6/site-packages/advntr/genome_analyzer.py", line 101, in print_genotype_in_vcf
    if genotype_result.copy_numbers is None:
AttributeError: 'tuple' object has no attribute 'copy_numbers'

command： advntr genotype --alignment_file NA12878.bam --models hg19_selected_VNTRs_Pacbio.db  --working_directory new_log --outfile advntr_new --outfmt vcf --pacbio

**Comment by Jong-hun-Park** [comment]
Hi,

Thank you for reporting the issue. 
VCF output was only available for short sequencing datasets as it hasn't fully tested on PacBio datasets.
I've fixed the issue, and they are now available by updating the code through Github.
I will soon release a new version including the updates, but if you need to use it before then, please update adVNTR using this [instruction](https://advntr.readthedocs.io/en/latest/installation.html#install-from-source-not-recommended)

**Comment by BrendaLee1** [comment]
Hi,
  First,thank you for your reply. I tried to update adVNTR via Bioconda and source code, but both of them failed, information as follows:
Bioconda:
Solving environment: failed
InvalidVersionSpecError: Invalid version spec: =2.7
source code:
I tried to install adVNTR with prefixed path and it also failed.

**_Genotype Error_**
I used the old version adVNTR(1.3) to identify NA12878 genotype and manually checked some of the results, I found that most of them were incorrect which made me very confused.
command： advntr genotype --alignment_file NA12878_chr3.bam --models hg19_selected_VNTRs_Pacbio.db --working_directory new_log --outfile advntr_test --outfmt vcf --pacbio

**Comment by BrendaLee1** [comment]
Hi!
   Firstly Thank you for your reply, I tyied your new version, but still cannot work on Pacbio sequence data. Information as blow:
I tested advntr by one chromosome's Pacbio sequence data, the error information below:
if genotype_result.copy_numbers is None:
AttributeError: 'NoneType' object has no attribute 'copy_numbers'

Then I use just the vntr ID to test advntr, error information as follows:
 self.print_genotype_in_bed_format(vntr_id, genotype_result.copy_numbers)
AttributeError: 'tuple' object has no attribute 'copy_numbers'

**Comment by Jong-hun-Park** [comment]
Hi,
Sorry for the late reply. Can you please let me know how you installed the new version? It's currently only available through github (not conda).

**Comment by Xiaodiao1111** [comment]
> 你好！ 首先感谢您的回复，我绑定了您的新版本，但仍然无法处理Pacbio序列数据。信息如下： 我用一条染色体的Pacbio序列数据测试了advntr，错误信息如下： if genotype_result.copy_numbers is None: AttributeError: 'NoneType' object has no attribute 'copy_numbers'
> 
> 然后我只使用vntr ID来测试advntr，错误信息如下： self.print_genotype_in_bed_format(vntr_id, genotype_result.copy_numbers) AttributeError: 'tuple' object has no attribute 'copy_numbers'
> 
> 所以我尝试了旧版本1.3.3，它运行成功。

Hello, may I ask how your problem was solved? I had a similar problem.

**Comment by Xiaodiao1111** [comment]
> 你好，
> 
> 感谢您报告该问题。 VCF 输出仅适用于短测序数据集，因为它尚未在 PacBio 数据集上进行全面测试。 我已经解决了这个问题，现在可以通过 Github 更新代码来使用它们。 我很快就会发布包含更新的新版本，但如果您需要在此之前使用它，请使用此[说明更新 adVNTR](https://advntr.readthedocs.io/en/latest/installation.html#install-from-source-not-recommended)

Hello, have you solved this problem? I have the same problem.
